values:
  - value: "God's Word"
    description: >-
      We value God's Word, the Bible, as solely authoritative and sufficient in all matters
      of belief and behavior for every believer's enjoyment of God and for the ministry of the church.
    references: 'Psa. 1:1–3; 2 Tim 3:16–17; 1 Pet 2:2; 2 Pet 1:2–4'
    image: /images/core-values/bible.jpg
  - value: Prayer
    description: >-
      We value prayer as the visible engine of all our efforts in ministry and worship.
      Fully relying on the Holy Spirit.
    references: 'Acts 2:42; Eph. 6:18–20; Phil 4:6; Col 4:2; 1 Thess. 5:16–18; 1 Cor 2:14–16; Zech 4:6'
    image: /images/core-values/prayer.jpg
  - value: Biblical Family Roles
    description: >-
      We value husbands, wives, and children fulfilling their biblical roles in the family and in the church.
    references: 'Deut. 6:4–9; Psa. 78:1–9; Eph. 6:4; 2 Tim 3:14–15'
    image: /images/core-values/biblicalfamilyroles.jpeg
  - value: Personal and Corporate Worship
    description: >-
      We value personal and corporate worship of God, which engages both the mind and the heart.
    references: 'John 4:23–24; Jam 4:8; Psa. 16:11; 2 Tim 4:1–4'
    image: /images/core-values/personalandcorporateworship.jpeg
  - value: Christ-Centered Relationships
    description: >-
      We value Christ-centered relationships, especially through the regular gathering of small groups
      focused on God's Word, prayer, and mutual love.
    references: 'John 13:34; Eph. 5:1–2; 1 Thess. 5:11; Heb 10:23–25; Jam 5:16'
    image: /images/core-values/christcenteredrelationship.jpg
  - value: Christlikeness
    description: >-
      We value corporately developing biblical knowledge, character, and actions that imitate Christ.
    references: 'Eph. 4:12; Col 1:28'
    image: /images/core-values/christlikeness.jpg
  - value: Faithful Service
    description: >-
      We value every believer faithfully serving in the body of Christ.
    references: 'Rom 12:9–13; 1 Pet 4:11–12; 1 Cor. 12:7; Eph. 4:11–13'
    image: /images/core-values/sundayschool.jpg
  - value: Gospel Outreach
    description: >-
      We value reaching those who do not know Christ in our communities and throughout the world.
    references: 'Matt 28:19–20; Acts 1:8; Rom 10:1; Col 4:2–4'
    image: null
  - value: Elder Leadership
    description: >-
      We value the submission to Christ's leadership, which is carried out by a biblically qualified
      team of elders.
    references: 'Acts 20:28; 1 Tim 3:1–7; Titus 1:5–9; 1 Pet 5:1–3; Heb. 13:17'
    image: null
  - value: Leader Equipping
    description: >-
      We value equipping leaders in the context of the local church.
    references: 'Eph. 4:11–12; 1 Tim 5:17'
    image: null
