primaryContactName: Mohan Nitta
phone1: (+91) 91829 49644
phone2: (+91) 95025 42648
addressLine1: 50-1-43, Ground Floor, ASR Nagar
addressLine2: Seethammadhara
city: Visakhapatnam
state: Andhra Pradesh
pincode: '530013'
youtubeUrl: https://www.youtube.com/@DanielSuryaAvula
danielsuryaUrl: https://www.danielsurya.in/
mapsUrl: >-
  https://www.google.com/maps/place/Grace+Life+Church,+Vizag/@17.7456557,83.312457,99m/data=!3m1!1e3!4m6!3m5!1s0x3a395d7a60e10f17:0x23137b54b808f3b2!8m2!3d17.745603!4d83.312793!16s%2Fg%2F11ghpmzkvl
